[tools]
rust = "nightly-2025-12-16"

[tasks.lint]
run = "cargo clippy"

[tasks.fix]
run = "cargo clippy --fix"

[tasks.format]
run = "cargo fmt"

[tasks.run]
run = "cargo run"

[tasks.test]
run = "cargo test"
