[tools]
rust = "latest"
pkl = "latest"

[tasks.lint]
run = "cargo clippy"

[tasks.fix]
run = "cargo clippy --fix"

[tasks.format]
run = "cargo fmt"

[tasks.run]
run = "cargo run"

[tasks.test]
run = "cargo test"
